version: 2
jobs:
  build:
     machine:
       image: ubuntu-1604:201903-01
     steps:
       - checkout
       - run:
           name: "Build the Meterian Scanner Docker image"
           command: |
              cd build
              ./buildDockerImage.sh --build-all
       - run:
           name: "Push Meterian Scanner Docker image to Docker Hub"
           command: |
              cd build
              echo full > ../version.txt
              ./push-docker-image-to-hub.sh
              echo java > ../version.txt
              ./push-docker-image-to-hub.sh
              echo web > ../version.txt
              ./push-docker-image-to-hub.sh
              echo dotnet > ../version.txt
              ./push-docker-image-to-hub.sh
              echo ruby > ../version.txt
              ./push-docker-image-to-hub.sh
              echo python > ../version.txt
              ./push-docker-image-to-hub.sh



workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:                                                                                                                                                          
    triggers:                                                                                                                                                             
      - schedule:                                                                                                                                                         
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - image-multi-version
    jobs:
      - build