jobs:
  build:
     machine:
       image: ubuntu-1604:201903-01

     steps:
       - checkout
       - run:
           name: "Build and push Meterian Scanner Docker image to Docker Hub"
           command: |
              cd build
              ./buildDockerImage.sh
              ./push-docker-image-to-hub.sh